name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
        
    - name: Restore dependencies
      run: nuget restore GITHubCICDTest.sln
      
    - name: Build Web App
      run: msbuild.exe GITHubCICDTest.sln /p:DeployOnBuild=true /p:platform="Any CPU" /p:configuration="Release"
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: "./_build"
    
 
 
