name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
        
    - name: Build and Publish Web App
      run: msbuild.exe GITHubCICDTest.sln /p:platform="Any CPU" /p:configuration="Release"
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: GITHubCICDTestBundle
        path: "./_build"
      
 
