name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  WEBAPP_NAME: GITHubCICDTest.sln     # set this to your application's name
  WEBAPP_PACKAGE_PATH: './_build'  # set this to the path to your web app project, defaults to the repository root
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir ${{ env.WEBAPP_PACKAGE_PATH }}
        
    - name: Restore dependencies
      run: nuget restore ${{ env.WEBAPP_NAME }}
      
    - name: Build Web App
      run: msbuild ${{ env.WEBAPP_NAME }} /p:Configuration=Release
    
    - name: Publish to folder
      run: msbuild ${{ env.WEBAPP_NAME }} /p:Configuration=Release /p:DeployOnBuild=true /t:WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=${{ env.WEBAPP_PACKAGE_PATH }} /p:PackageAsSingleFile=false

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: ${{ env.WEBAPP_PACKAGE_PATH }}
    
 
 
