name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1    

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build Solution
      run: |
        msbuild.exe GITHubCICDTest.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
    
    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/GITHubCICDTest

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/GITHubCICDTest
      
 
